### ISSUE TITLE
Question about C&S hyperparameter alpha

### ISSUE THREAD

**Issue by lijiong20** [skepsun/SAGN_with_SLE#2]
I'm wondering how do you get C&S hyperparam _alpha_  in ogbn-product as

`--correction-alpha 0.4553513529697225 \
--smoothing-alpha 0.7153479868942039 \`

Did you tune it on valid-set or test-set? what's your strategy to find alpha

Thank's for your reply

**Comment by skepsun** [comment]
We searched hyperparameters with 300 loops using Optuna. The target metric is set as the test accuracy.

Thank you for reminding us that we should tune on valid set. We also note that `scale` should be 20, the same value in the search script. We searched hyperparameters again using valid accuracy with the same other settings. The final optimal hyperparameters are:
```
python -u ../../src/post_process.py \
    --dataset ogbn-products \
    --gpu $gpu \
    --model sagn \
    --K 3 \
    --label-K 14 \
    --use-labels \
    --stage 3 \
    --num-correction-layers 50 \
    --num-smoothing-layers 50 \
    --correction-alpha 0.4241429558473879 \
    --smoothing-alpha 0.4119142023305396 \
    --correction-adj DAD \
    --smoothing-adj DAD \
    --scale 20
```

The associated results are:
```
Train score: 0.9982±0.0001
Valid score: 0.9322±0.0003
Test score: 0.8481±0.0012
```
They are a bit lower than reported results. We will do more research about hyperparamter searching for C&S.
Thanks again for your question!
